apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      k8s-app: {{ .Values.name }}
  ingress:
  - ports:
    - port: {{ .Values.ports.dns.targetPort }}
      protocol: UDP
    - port: {{ .Values.ports.dns.targetPort }}
      protocol: TCP
    - port: {{ .Values.ports.dns.port }}
      protocol: UDP
    - port: {{ .Values.ports.dns.port }}
      protocol: TCP
  - ports:
    - port: {{ .Values.ports.prometheus }}
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
