{{- if (gt (.Values.hpa.maxReplicas | int) 1) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
{{- end }}
