version: 2.1
orbs:
  architect: giantswarm/architect@0.4.2

workflows:
  version: 2
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push coredns-app chart"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "coredns-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
