version: 2.1
orbs:
  architect: giantswarm/architect@4.33.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: "push-to-default-app-catalog"
          context: architect
          executor: "app-build-suite"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "coredns-app"
          persist_chart_archive: true
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          app-test-suite_version: "v0.4.1"
          app-test-suite_container_tag: "0.4.1"
          filters:
            # Do not trigger the job on merge to main.
            branches:
              ignore:
                - main
          requires:
            - push-to-default-app-catalog
