{{- if .Values.adopter.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: kube-system
  name: coredns
  labels:
    {{- include "labels.common" . | nindent 8 }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    meta.helm.sh/release-name: coredns
    meta.helm.sh/release-namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
  ingress:
  - ports:
    - port: 1053
      protocol: UDP
    - port: 1053
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - ports:
    - port: 9153
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
{{- end }}
