{{- if .Values.adopter.enabled }}
apiVersion: kyverno.io/v1
kind: PolicyException
metadata:
  name: coredns-adopter-exception
  namespace: kube-system
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
spec:
  exceptions:
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  match:
    any:
    - resources:
        kinds:
        - Job
        - Pod
        names:
        - coredns-adopter
        - coredns-adopter-*
        namespaces:
        - kube-system
{{- end }}
