{{- if .Values.adopter.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredns-adopter
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups: ["", "*"]
  resources: ["*"]
  resourceNames: ["coredns", "coredns-workers", "kube-dns", "system:coredns", "coredns-adopter"]
  verbs: ["*"]
- apiGroups: ["", "*"]
  resources: ["*"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["services"]
  resourceNames: ["kubernetes"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: coredns-adopter
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
subjects:
- kind: ServiceAccount
  name: coredns-adopter
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: coredns-adopter
  apiGroup: rbac.authorization.k8s.io
{{- end }}
