{{- if .Values.adopter.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns
  namespace: kube-system
  labels:
    {{- include "labels.common" . | nindent 8 }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    meta.helm.sh/release-name: coredns
    meta.helm.sh/release-namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns-adopter
  namespace: kube-system
  labels:
    {{- include "labels.common" . | nindent 8 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
{{- end }}
