# Default values for coredns-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: coredns
namespace: kube-system
serviceType: managed

# provider is dynamic environment value, which comes from application catalog configuration
# applies only to Giant Swarm clusters
provider: ""

userID: 33
groupID: 33

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 50
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
  metrics: []
  # The stabilization window is used to restrict the flapping of replica count
  # when the metrics used for scaling keep fluctuating.
  # This is very useful for large scale clusters to prevent the CoreDNS from flapping
  # while kube-proxy is taking long time to add the scaled up pods to the service
  # In such cases set this value to at least 1800
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1800

configmap:
# Uncomment "autopath" to enable DNS autopath https://coredns.io/plugins/autopath/
# autopath: "@kubernetes"
  cache: 30
  custom: ""
  log: |
    denial
    error

  # Uncomment and define `forward` to enable and configure forwarding rules for CoreDNS forward plugin (for syntax see https://coredns.io/plugins/forward/)
  # forward: . 192.168.1.1 /etc/resolv.conf
  # forwardOptions: |
  #   policy random

image:
  registry: docker.io
  name: giantswarm/coredns
  tag: 1.9.3

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1

podDisruptionBudget:
  maxUnavailable: 25%

ports:
  dns:
    name: dns
    targetPort: 1053
    port: 53
  prometheus: 9153

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

cluster:
  calico:
    CIDR: 192.168.0.0/16
  kubernetes:
    API:
      clusterIPRange: 172.31.0.0/16
    DNS:
      IP: 172.31.0.10
    clusterDomain: cluster.local

loadbalancePolicy: round_robin

mastersInstance:
  nodeSelector:
    "node-role.kubernetes.io/control-plane": '""'

# Uncomment and define `additionalLocalZones` to add additional local zones to CoreDNS config
# additionalLocalZones: []

cloudSpecificSettings:
  additionalZones: []
  azure:
    defaultZones:
    - windows.net
    - onmicrosoft.com
    - azure-api.net
    - cloudapp.net
    - azurecr.io
    - azurecontainer.io
    - vo.msecnd.net
    - azure.com
    - azurefd.net
    - vault.azure.net
    - azmk8s.io
    - azure-mobile.net
    - azureedge.net
    - trafficmanager.net
    - azurewebsites.net
    - visualstudio.com
    forwardIPs:
    - 168.63.129.16
  aws:
    defaultZones:
    - compute.internal
    - amazonaws.com
    forwardIPs:
    - 169.254.169.253

test:
  image:
    name: giantswarm/alpine-testing
    tag: 0.1.1
