# Default values for coredns-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: coredns
namespace: kube-system
serviceType: managed

userID: 33
groupID: 33

hpa:
  minReplicas: 2
  maxReplicas: 50
  targetCPUUtilizationPercentage: 70

configmap:
# Uncomment "autopath" to enable DNS autopath https://coredns.io/plugins/autopath/
# autopath: "@kubernetes"
  cache: 30
  custom: ""
  log: |
    denial
    error

  # Uncomment and define `forward` to enable and configure forwarding rules for CoreDNS forward plugin (for syntax see https://coredns.io/plugins/forward/)
  # forward: . 192.168.1.1 /etc/resolv.conf
  # forwardOptions: |
  #   policy random

image:
  registry: docker.io
  name: giantswarm/coredns
  tag: 1.8.7

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1

ports:
  dns:
    name: dns
    targetPort: 1053
    port: 53
  prometheus: 9153

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 250m
    memory: 192Mi

cluster:
  calico:
    CIDR: 192.168.0.0/16
  kubernetes:
    API:
      clusterIPRange: 172.31.0.0/16
    DNS:
      IP: 172.31.0.10
    clusterDomain: cluster.local

loadbalancePolicy: round_robin

test:
  image:
    name: giantswarm/alpine-testing
    tag: 0.1.1
